name: "Terraform Actions"

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'us-east-1'
      TF_VERSION: '1.4.0'

    steps:
      - name: 'Git Checkout'
        uses: actions/checkout@v3

      - name: 'AWS Configure'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-key: ${{ secrets.SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v1
        with: 
          terraform_version: ${{ env.TF_VERSION }}

      - name: 'Terraform Destroy'
        run: terraform destroy -auto-approve
